---

- name: "Install and setup AIDE"
  block:

  - name: "The RHEL 8 operating system must use a file integrity tool to verify correct operation of all security functions."
    tags:
      - V251710
      - medium
      - RHEL-08-010359
      - SV-251710r854081_rule
      - C-55147r809352_chk
      - F-55101r809353_fix
    when:
      - "'aide' not in ansible_facts.packages"
    ansible.builtin.package:
      update_cache: true
      state: present
      name:
        - aide
    register: aide_install

  - name: "Check for AIDE database"
    ansible.builtin.stat:
      path: /var/lib/aide/aide.db.gz
    register: aide_database

  - name: "Initialize and deploy AIDE database"
    when: aide_install.changed or aide_database.stat.exists == false
    # If aide is newly installed you will need to run /usr/sbin/aide --init to Initialize the database.
    # Once complete you will need to move /var/lib/aide/aide.db.new.gz to /var/lib/aide/aide.db.new.gz
    block:

    - name: "Initialize the database"
      ansible.builtin.command: /usr/sbin/aide --init
      args:
        creates: /var/lib/aide/aide.db.new.gz

    - name: "move /var/lib/aide/aide.db.new.gz to /var/lib/aide/aide.db.gz"
      ansible.builtin.copy:
        remote_src: True
        src: /var/lib/aide/aide.db.new.gz
        dest: /var/lib/aide/aide.db.gz

  - name: "The RHEL 8 file integrity tool must notify the system administrator when changes to the baseline configuration or anomalies in the operation of any security functions are discovered within an organizationally defined frequency."
    tags:
      - V230263
      - medium
      - RHEL-08-010360
      - SV-230263r858725_rule
      - C-32932r858724_chk
      - F-32907r567536_fix
      - SRG-OS-000363-GPOS-00150
      - SRG-OS-000446-GPOS-00200
      - SRG-OS-000447-GPOS-00201
    ansible.builtin.template:
      src: aide.cron.j2
      dest: "etc/cron.daily/aide"
      owner: root
      group: root
      mode: 0600
      force: true

# - name: "Configure rules for /etc/aide.conf"
#   block:

#   - name: "The RHEL 8 file integrity tool must be configured to verify extended attributes."
#     tags:
#       - V230551
#       - low
#       - RHEL-08-040300
#       - SV-230551r627750_rule
#       - C-33220r568399_chk
#       - F-33195r568400_fix
#     ansible.builtin.lineinfile:
#       name: "/etc/aide.conf"
#       create: true
#       mode: 0600
#       regex: "{{ V230551.regex }}"
#       line: "{{ V230551.line }}"
#     loop_control:
#       loop_var: V230551
#     loop:
#       - { regex: '^(#*|#\s*|\s*)disk_error_action(\s*)', line: "disk_error_action = HALT" }


#   #   block:
#   #     ansible.builtin.debug:
#   #       msg: >
#   #        Description:
#   #           Extended attributes in file systems are used to contain arbitrary data and file metadata with
#   #           security implications.

#   #           RHEL 8 installatim    on media come with a file integrity tool, Advanced Intrusion Detection Environment
#   #           (AIDE).
#   #         Check:
#   #           Verify the file integrity tool is configured to verify extended attributes.

#   #           If AIDE is not installed, ask the System Administrator how file integrity checks are performed on
#   #           the system.

#   #           Note: AIDE is highly configurable at install time. This requirement assumes the "aide.conf" file is
#   #           under the "/etc" directory.

#   #           Use the following command to determine if the file is in another location:

#   #           $ sudo find / -name aide.conf

#   #           Check the "aide.conf" file to determine if the "xattrs" rule has been added to the rule list being
#   #           applied to the files and directories selection lists.

#   #           An example rule that includes the "xattrs" rule follows:

#   #            = p+i+n+u+g+s+m+S+sha512+acl+xattrs+selinux
#   #           /bin All # apply the custom rule to the files in bin
#   #           /sbin All # apply the same custom rule to the files in sbin

#   #           If the "xattrs" rule is not being used on all uncommented selection lines in the "/etc/aide.conf"
#   #           file, or extended attributes are not being checked by another file integrity tool, this is a
#   #           finding.
#   #         Fix:
#   #           Configure the file integrity tool to check file and directory extended attributes.

#   #           If AIDE is installed, ensure the "xattrs" rule is present on all uncommented file and directory
#   #           selection lists.




#   - name: "The RHEL 8 file integrity tool must be configured to verify Access Control Lists (ACLs)."
#     tags:
#       - V230552
#       - low
#       - RHEL-08-040310
#       - SV-230552r627750_rule
#       - C-33221r568402_chk
#       - F-33196r568403_fix
#   #   block:
#   #     ansible.builtin.debug:
#   #       msg: >
#   #        Description:
#   #           ACLs can provide permissions beyond those permitted through the file mode and must be verified by
#   #           file integrity tools.

#   #           RHEL 8 installation media come with a file integrity tool, Advanced Intrusion Detection Environment
#   #           (AIDE).
#   #         Check:
#   #           Verify the file integrity tool is configured to verify ACLs.

#   #           Note: AIDE is highly configurable at install time. This requirement assumes the "aide.conf" file is
#   #           under the "/etc" directory.

#   #           If AIDE is not installed, ask the System Administrator how file integrity checks are performed on
#   #           the system.

#   #           Use the following command to determine if the file is in a location other than
#   #           "/etc/aide/aide.conf":

#   #           $ sudo find / -name aide.conf

#   #           Check the "aide.conf" file to determine if the "acl" rule has been added to the rule list being
#   #           applied to the files and directories selection lists with the following command:

#   #           $ sudo egrep "[+]?acl" /etc/aide.conf

#   #           VarFile = OwnerMode+n+l+X+acl

#   #           If the "acl" rule is not being used on all selection lines in the "/etc/aide.conf" file, is
#   #           commented out, or ACLs are not being checked by another file integrity tool, this is a finding.
#   #         Fix:
#   #           Configure the file integrity tool to check file and directory ACLs.

#   #           If AIDE is installed, ensure the "acl" rule is present on all file and directory selection lists.
#     ansible.builtin.lineinfile:
#       name: "/etc/aide.conf"
#       create: true
#       mode: 0600
#       regex: "{{ V230551.regex }}"
#       line: "{{ V230551.line }}"
#     loop_control:
#       loop_var: V230551
#     loop:
#       - { regex: '^(#*|#\s*|\s*)VarFile(\s*)', line: "VarFile = OwnerMode+n+l+X+acl" }


#   # - name: "RHEL 8 must use cryptographic mechanisms to protect the integrity of audit tools."
#   #   tags:
#   #       - V230475
#   #       - medium
#   #       - RHEL-08-030650
#   #       - SV-230475r833333_rule
#   #       - C-33144r833332_chk
#   #       - F-33119r568172_fix
#   #   block:
#   #     ansible.builtin.debug:
#   #       msg: >
#   #        Description:
#   #           Protecting the integrity of the tools used for auditing purposes is a critical step toward ensuring
#   #           the integrity of audit information. Audit information includes all information (e.g., audit records,
#   #           audit settings, and audit reports) needed to successfully audit information system activity.

#   #           Audit tools include, but are not limited to, vendor-provided and open source audit tools needed to
#   #           successfully view and manipulate audit information system activity and records. Audit tools include
#   #           custom queries and report generators.

#   #           It is not uncommon for attackers to replace the audit tools or inject code into the existing tools
#   #           with the purpose of providing the capability to hide or erase system activity from the audit logs.

#   #           To address this risk, audit tools must be cryptographically signed to provide the capability to
#   #           identify when the audit tools have been modified, manipulated, or replaced. An example is a checksum
#   #           hash of the file or files.
#   #         Check:
#   #           Verify that Advanced Intrusion Detection Environment (AIDE) is properly configured to use
#   #           cryptographic mechanisms to protect the integrity of audit tools.

#   #           If AIDE is not installed, ask the System Administrator how file integrity checks are performed on
#   #           the system.

#   #           Check the selection lines to ensure AIDE is configured to add/check with the following command:

#   #           $ sudo egrep '(\/usr\/sbin\/(audit|au|rsys))' /etc/aide.conf

#   #           /usr/sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/rsyslogd p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512

#   #           If any of the audit tools listed above do not have an appropriate selection line, ask the system
#   #           administrator to indicate what cryptographic mechanisms are being used to protect the integrity of
#   #           the audit tools. If there is no evidence of integrity protection, this is a finding.
#   #         Fix:
#   #           Add or update the following lines to "/etc/aide.conf", to protect the integrity of the audit tools.

#   #           # Audit Tools
#   #           /usr/sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/rsyslogd p+i+n+u+g+s+b+acl+xattrs+sha512
#   #           /usr/sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512

