---

- name: "RHEL 8 must specify the default \"include\" directory for the /etc/sudoers file."
  tags:
    - V251711
    - medium
    - RHEL-08-010379
    - SV-251711r833385_rule
    - C-55148r833384_chk
    - F-55102r809356_fix
  block:

  - name: "Check /etc/sudoers for \"inlcude\""
    ansible.builtin.lineinfile:
      name: "/etc/sudoers"
      create: true
      owner: root
      group: root
      mode: 0400
      regex: "{{ V251711a.regex }}"
      line: "{{ V251711a.line }}"
    loop_control:
      loop_var: V251711a
    loop:
      - { regex: '^(#*|#\s*|\s*)include', line: "#includedir /etc/sudoers.d" }
    validate: /usr/sbin/visudo -cf %s

  - name: "Check /etc/sudoers.d/ for \"inlcude\""
    ansible.builtin.lineinfile:
      path: "{{ V251711b }}"
      owner: root
      group: root
      mode: 0400
      regex: '^(#*|#\s*|\s*)include'
      state: absent
    loop_control:
      loop_var: V251711b
    with_fileglob:
      - '/etc/sudoers.d/*'
    validate: /usr/sbin/visudo -cf %s

- name: "RHEL 8 must restrict privilege elevation to authorized personnel."
  tags:
      - V237641
      - medium
      - RHEL-08-010382
      - SV-237641r646893_rule
      - C-40860r646891_chk
      - F-40823r646892_fix
- name: "Check /etc/sudoers.d/ for \"ALL     ALL=\""
  ansible.builtin.lineinfile:
    path: "{{ V237641 }}"
    owner: root
    group: root
    mode: 0400
    regex: '^(#*|#\s*|\s*)ALL\s*ALL='
    state: absent
  loop_control:
    loop_var: V237641
  with_fileglob:
    - '/etc/sudoers'
    - '/etc/sudoers.d/*'
  validate: /usr/sbin/visudo -cf %s

# - name: "RHEL 8 must use the invoking user's password for privilege escalation when using \"sudo\"."
#   tags:
#     - V237642
#     - medium
#     - RHEL-08-010383
#     - SV-237642r861086_rule
#     - C-40861r858759_chk
#     - F-40824r858760_fix
#   block:
#   - name: "Check sudoers for defaults"
#     ansible.builtin.lineinfile:
#       name: "/etc/sudoers"
#       create: true
#       owner: root
#       group: root
#       mode: 0400
#       regex: "{{ V237642a.regex }}"
#       line: "{{ V237642a.line }}"
#     loop_control:
#       loop_var: V237642a
#     loop:
#       - regex: '^(#*|#\s*|\s*|.*)!targetpw'
#         line: "Defaults !targetpw"
#       - regex: '^(#*|#\s*|\s*|.*)!rootpw'
#         line: "Defaults !rootpw"
#       - regex: '^(#*|#\s*|\s*|.*)!runaspw'
#         line: "Defaults !runaspw"
#     validate: /usr/sbin/visudo -cf %s

#   - name: "Check sudoers.d/ for defaults"
#     ansible.builtin.lineinfile:
#       name: "/etc/sudoers"
#       create: false
#       owner: root
#       group: root
#       mode: 0400
#       regex: "{{ V237642a.regex }}"
#       line: "{{ V237642a.line }}"
#     loop_control:
#       loop_var: V237642a
#     loop:
#       - regex: '^(#*|#\s*|\s*|.*)!targetpw'
#         line: "Defaults !targetpw"
#       - regex: '^(#*|#\s*|\s*|.*)!rootpw'
#         line: "Defaults !rootpw"
#       - regex: '^(#*|#\s*|\s*|.*)!runaspw'
#         line: "Defaults !runaspw"
#     with_fileglob:
#     - '/etc/sudoers'
#     - '/etc/sudoers.d/*'
#     validate: /usr/sbin/visudo -cf %s




# - name: "RHEL 8 must require users to provide a password for privilege escalation."
#   tags:
#       - V230271
#       - medium
#       - RHEL-08-010380
#       - SV-230271r854026_rule
#       - C-32940r854024_chk
#       - F-32915r854025_fix
#   block:
#     ansible.builtin.debug:
#       msg: >
#        Description:
#           Without reauthentication, users may access resources or perform tasks for which they do not have
#           authorization.

#           When operating systems provide the capability to escalate a functional capability, it is critical
#           the user reauthenticate.

#           Satisfies: SRG-OS-000373-GPOS-00156, SRG-OS-000373-GPOS-00157, SRG-OS-000373-GPOS-00158
#         Check:
#           Verify that "/etc/sudoers" has no occurrences of "NOPASSWD".

#           Check that the "/etc/sudoers" file has no occurrences of "NOPASSWD" by running the following
#           command:

#           $ sudo grep -i nopasswd /etc/sudoers /etc/sudoers.d/*

#           %admin ALL=(ALL) NOPASSWD: ALL

#           If any occurrences of "NOPASSWD" are returned from the command and have not been documented with the
#           ISSO as an organizationally defined administrative group utilizing MFA, this is a finding.
#         Fix:
#           Remove any occurrence of "NOPASSWD" found in "/etc/sudoers" file or files in the "/etc/sudoers.d"
#           directory.

# - name: "RHEL 8 must require users to reauthenticate for privilege escalation."
#   tags:
#       - V230272
#       - medium
#       - RHEL-08-010381
#       - SV-230272r854027_rule
#       - C-32941r567562_chk
#       - F-32916r567563_fix
#   block:
#     ansible.builtin.debug:
#       msg: >
#        Description:
#           Without reauthentication, users may access resources or perform tasks for which they do not have
#           authorization.

#           When operating systems provide the capability to escalate a functional capability, it is critical
#           the user reauthenticate.

#           Satisfies: SRG-OS-000373-GPOS-00156, SRG-OS-000373-GPOS-00157, SRG-OS-000373-GPOS-00158
#         Check:
#           Verify that "/etc/sudoers" has no occurrences of "!authenticate".

#           Check that the "/etc/sudoers" file has no occurrences of "!authenticate" by running the following
#           command:

#           $ sudo grep -i !authenticate /etc/sudoers /etc/sudoers.d/*

#           If any occurrences of "!authenticate" return from the command, this is a finding.
#         Fix:
#           Remove any occurrence of "!authenticate" found in "/etc/sudoers" file or files in the
#           "/etc/sudoers.d" directory.

# - name: "RHEL 8 must require re-authentication when using the \"sudo\" command."
#   tags:
#       - V237643
#       - medium
#       - RHEL-08-010384
#       - SV-237643r861088_rule
#       - C-40862r861087_chk
#       - F-40825r858763_fix
#   block:
#     ansible.builtin.debug:
#       msg: >
#        Description:
#           Without re-authentication, users may access resources or perform tasks for which they do not have
#           authorization.

#           When operating systems provide the capability to escalate a functional capability, it is critical
#           the organization requires the user to re-authenticate when using the "sudo" command.

#           If the value is set to an integer less than 0, the user's time stamp will not expire and the user
#           will not have to re-authenticate for privileged actions until the user's session is terminated.
#         Check:
#           Verify the operating system requires re-authentication when using the "sudo" command to elevate
#           privileges.

#           $ sudo grep -ir 'timestamp_timeout' /etc/sudoers /etc/sudoers.d
#           /etc/sudoers:Defaults timestamp_timeout=0

#           If conflicting results are returned, this is a finding.

#           If "timestamp_timeout" is set to a negative number, is commented out, or no results are returned,
#           this is a finding.
#         Fix:
#           Configure the "sudo" command to require re-authentication.
#           Edit the /etc/sudoers file:
#           $ sudo visudo

#           Add or modify the following line:
#           Defaults timestamp_timeout=[value]
#           Note: The "[value]" must be a number that is greater than or equal to "0".

#           Remove any duplicate or conflicting lines from /etc/sudoers and /etc/sudoers.d/ files.


# #   ansible.builtin.template:
# #     src: 00-ansible.j2
# #     dest: /etc/sudoers.d/00-ansible
# #     owner: root
# #     group: root
# #     mode: '0440'
# #     force: true
# #     validate: /usr/sbin/visudo -cf %s
